services:
  tomcat:
    image: eyodevops/ecommerce-docker:1.1
    container_name: ecommerce-app
    ports:
      - "8080:8080"
      - "8088:8088"
    networks:
      - app-network

  mysql:
    image: mysql:8.3.0
    env_file:
      - .env
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ecommerce_app
    volumes:
      - ./sql:/docker-entrypoint-initdb.d 
    networks:
      - app-network
      
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    environment:
      PMA_HOST: ecommerce-db
      PMA_PORc: 3306
      PPMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge
